const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Keyboard: 0},
	{Array: 0},
	{Array2: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{px: 0},
	{py: 0},
	{sElement: 0},
	{Tween: 0},
	{sFood: 0},
	{num: 0},
	{sSnake: 0},
	{sBG: 0},
	{Sine: 0},
	{sGrass: 0},
	{sName: 0},
	{sGameBG: 0},
	{sGameOver: 0},
	{sBlik: 0},
	{sPause: 0},
	{Particles: 0},
	{bSound: 0},
	{bStart: 0},
	{bPause: 0},
	{bRestart: 0},
	{bClose: 0},
	{bDirrection: 0},
	{tScoreGO: 0},
	{tScore: 0},
	{tInstruction: 0},
	{tEat: 0},
	{tMenuGO_Score: 0},
	{tGO_desc: 0},
	{AJAX_status: 0},
	{WallObstacle: 0},
	{sDeadCell: 0},
	{moregamessheet: 0},
	{Asset: 0},
	{BG: 0},
	{LogoApp: 0},
	{LeaderboardBtn: 0},
	{FadeBG: 0},
	{BillboardNew: 0},
	{fBts: 0},
	{sounds: 0},
	{soundName: 0},
	{partsCount: 0},
	{direction: 0},
	{startGame: 0},
	{snakeSpeed: 0},
	{snakeX: 0},
	{snakeY: 0},
	{ox: 0},
	{oy: 0},
	{od: 0},
	{bestScore: 0},
	{score: 0},
	{MOVE_SPEED: 0},
	{fx: 0},
	{fy: 0},
	{free: 0},
	{totalSkulls: 0},
	{stopLoop: 0},
	{ax: 0},
	{ay: 0},
	{dir: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Array2: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	sElement: class extends self.ISpriteInstance {},
	sFood: class extends self.ISpriteInstance {},
	sSnake: class extends self.ISpriteInstance {},
	sBG: class extends self.ISpriteInstance {},
	sGrass: class extends self.ISpriteInstance {},
	sName: class extends self.ISpriteInstance {},
	sGameBG: class extends self.ISpriteInstance {},
	sGameOver: class extends self.ISpriteInstance {},
	sBlik: class extends self.ISpriteInstance {},
	sPause: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	bSound: class extends self.ISpriteInstance {},
	bStart: class extends self.ISpriteInstance {},
	bPause: class extends self.ISpriteInstance {},
	bRestart: class extends self.ISpriteInstance {},
	bClose: class extends self.ISpriteInstance {},
	bDirrection: class extends self.ISpriteInstance {},
	tScoreGO: class extends self.ITextInstance {},
	tScore: class extends self.ITextInstance {},
	tInstruction: class extends self.ITextInstance {},
	tEat: class extends self.ITextInstance {},
	tMenuGO_Score: class extends self.ITextInstance {},
	tGO_desc: class extends self.ITextInstance {},
	AJAX_status: class extends self.ITextInstance {},
	WallObstacle: class extends self.ISpriteInstance {},
	sDeadCell: class extends self.ISpriteInstance {},
	moregamessheet: class extends self.ISpriteInstance {},
	Asset: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	LogoApp: class extends self.ISpriteInstance {},
	LeaderboardBtn: class extends self.ISpriteInstance {},
	FadeBG: class extends self.ISpriteInstance {},
	BillboardNew: class extends self.ISpriteInstance {},
	fBts: class extends self.ISpriteInstance {}
}